#!/usr/bin/env bash
# Install and set up haproxy for two servers

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web01 and web01 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option  httpclose
   option  forwardfor
   server 152610-web-02 54.165.186.92:80 check
   server 152610-web-01 3.90.65.5:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
