#!/usr/bin/env bash
# create a mysql database backup and archive it

mysqldump --all-databases -u root -p="$1" > backup.sql
day=$(date + "%d")
month=$(date + "%m")
year=$(date + "%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf $"file_name" backup.sql

echo "MySQL dump created and compressed to $file_name"

