#!/usr/bin/env bash
# script that does the following:
# Creates the file /var/run/myscript.pid containing its PID,
# Displays To infinity and beyond indefinitely,
# Displays I hate the kill command when receiving a SIGTERM signal,
# Displays Y U no love me?! when receiving a SIGINT signal,
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
echo $$ > /var/run/myscript.pid
while true
    do
        echo "To infinity and beyond"
    done
rm /var/run/myscript.pid
