#!/usr/bin/env bash
# localhost now resolves to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
